# GPU configuration
CUDA_VISIBLE_DEVICES: "0"

# Benchmark settings
ITERATIONS: 1
MAX_TEST_DURATION: 30  # 5 minutes in seconds

# Server experiment settings
LAMBDA_QPS_ARRAY:
  - 0.014467592592592592

# LLM models to benchmark
LLM_MODELS:
  - "Qwen/Qwen2-7B-Instruct"
  - "meta-llama/Llama-3.1-8B-Instruct"
  - "facebook/opt-125m"
  - "Qwen/Qwen2.5-7B-Instruct"
  - "meta-llama/Llama-3.2-1B-Instruct"
  - "Qwen/Qwen3-0.6B"
  - "Gensyn/Qwen2.5-0.5B-Instruct"
  - "Qwen/Qwen2.5-7B-Instruct-1M"
  - "google/gemma-3-1b-it"
  - "mistralai/Mistral-7B-Instruct-v0.2"
  - "Gensyn/Qwen2.5-1.5B-Instruct"
  - "Qwen/Qwen3-8B"
  - "meta-llama/Llama-3.2-3B-Instruct"
  - "Qwen/Qwen3-1.7B"
  - "meta-llama/Meta-Llama-3-8B-Instruct"
  - "Qwen/Qwen2.5-3B-Instruct"
  - "context-labs/meta-llama-Llama-3.2-3B-Instruct-FP16"
  - "apple/OpenELM-1_1B-Instruct"
  - "Qwen/Qwen3-4B"
  - "meta-llama/Llama-2-7b-chat-hf"
  - "deepseek-ai/DeepSeek-R1-Distill-Llama-8B"
  - "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  - "Orenguteng/Llama-3-8B-Lexi-Uncensored"
  - "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
  - "meta-llama/Llama-2-7b-hf"
  - "liuhaotian/llava-v1.5-7b"
  - "naver-hyperclovax/HyperCLOVAX-SEED-Vision-Instruct-3B"
  - "Qwen/Qwen1.5-0.5B-Chat"
  - "mistralai/Mistral-7B-v0.1"
  - "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B"
  - "bigscience/bloomz-560m"
  - "mistralai/Mixtral-8x7B-Instruct-v0.1"
  - "HuggingFaceH4/zephyr-7b-beta"
  - "deepseek-ai/DeepSeek-R1-0528-Qwen3-8B"
  - "HuggingFaceTB/SmolLM2-135M-Instruct"
  - "JackFram/llama-160m"
  - "nvidia/Llama-3.1-Nemotron-Nano-8B-v1"
  - "Qwen/Qwen2-1.5B-Instruct"
  - "Qwen/Qwen3-Reranker-0.6B"
  - "meta-llama/Llama-Guard-3-8B"
  - "Alibaba-NLP/gte-Qwen2-7B-instruct"
  - "JackFram/llama-68m"
  - "NovaSearch/stella_en_1.5B_v5"
  - "google/gemma-2-2b-it"
  - "google/gemma-2b-it"
  - "MLP-KTLim/llama-3-Korean-Bllossom-8B"
  - "Qwen/Qwen2.5-Coder-7B-Instruct"
  - "google/gemma-2-2b"
  - "google/gemma-2b"
  - "Qwen/Qwen1.5-4B-Chat"
  - "bigcode/starcoder2-3b"
  - "teknium/OpenHermes-2.5-Mistral-7B"
  - "lmsys/vicuna-7b-v1.5"
  - "unsloth/Meta-Llama-3.1-8B-Instruct"
  - "Qwen/Qwen2.5-Coder-3B-Instruct"
  - "codellama/CodeLlama-7b-Instruct-hf"
  - "tiiuae/falcon-rw-1b"
  - "allenai/Molmo-7B-D-0924"
  - "LGAI-EXAONE/EXAONE-3.5-7.8B-Instruct"
  - "ibm-granite/granite-3.3-8b-instruct"
  - "Qwen/Qwen2-0.5B-Instruct"
  - "HuggingFaceTB/SmolLM-135M"
  - "EleutherAI/gpt-j-6b"
  - "tiiuae/falcon-7b-instruct"
  - "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct"
  - "facebook/opt-350m"
  - "bigscience/bloom-560m"
  - "AI-Sweden-Models/gpt-sw3-126m"
  - "GSAI-ML/LLaDA-8B-Instruct"
  - "facebook/opt-1.3b"
  - "EleutherAI/gpt-neo-1.3B"
  - "EleutherAI/pythia-14m"
  - "agentica-org/DeepScaleR-1.5B-Preview"
  - "HuggingFaceTB/SmolLM2-360M-Instruct"
  - "Alibaba-NLP/gte-Qwen2-1.5B-instruct"
  - "allenai/OLMo-7B-hf"
  - "deepseek-ai/deepseek-coder-6.7b-instruct"
  - "DAMO-NLP-SG/VideoLLaMA3-7B"
  - "google/gemma-2-9b-it"
  - "EleutherAI/pythia-70m-deduped"
  - "ibm-granite/granite-3.3-2b-instruct"
  - "ggml-org/stories15M_MOE"
  - "google/gemma-1.1-2b-it"
  - "google/gemma-3-1b-pt"
  - "allenai/OLMoE-1B-7B-0924"
  - "h2oai/h2ovl-mississippi-2b"
  - "deepseek-ai/deepseek-llm-7b-chat"
  - "google/gemma-2-9b"
  - "Qwen/Qwen2.5-Math-7B"
  - "mosaicml/mpt-7b-chat"
  - "lmms-lab/llava-onevision-qwen2-7b-ov"
  - "LGAI-EXAONE/EXAONE-3.0-7.8B-Instruct"
  - "fdtn-ai/Foundation-Sec-8B"
  - "SVECTOR-CORPORATION/Akshara-8B-Llama-Multilingual-V0.1"
  - "elyza/Llama-3-ELYZA-JP-8B"
  - "EleutherAI/gpt-neo-125m"
  - "google/gemma-7b-it"
  - "EleutherAI/pythia-160m"
  - "google/gemma-7b"
  - "Qwen/Qwen3-Reranker-4B"
  - "state-spaces/mamba-130m-hf"
  - "huggyllama/llama-7b"
  - "ibm-research/PowerMoE-3b"
  - "Qwen/Qwen1.5-7B-Chat"
  - "NousResearch/Hermes-3-Llama-3.1-8B"
  - "Qwen/Qwen2.5-Math-1.5B-Instruct"
  - "AI-Sweden-Models/gpt-sw3-356m"
  - "liuhaotian/llava-v1.6-mistral-7b"
  - "ibm-granite/granite-3.1-8b-instruct"
  - "robowaifudev/megatron-gpt2-345m"
  - "llm-jp/llm-jp-3-7.2b-instruct3"
  - "HuggingFaceTB/SmolLM3-3B"
  - "HuggingFaceTB/SmolLM2-1.7B-Instruct"
  - "allenai/OLMo-1B-0724-hf"
  - "allenai/Llama-3.1-Tulu-3-8B-SFT"
  - "mistralai/Mixtral-8x7B-v0.1"
  - "Qwen/Qwen1.5-1.8B-Chat"
  - "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8"
  - "dnotitia/Smoothie-Qwen3-1.7B"
  - "facebook/opt-6.7b"
  - "LGAI-EXAONE/EXAONE-Deep-7.8B"
  - "internlm/internlm3-8b-instruct"
  - "facebook/opt-2.7b"
  - "winninghealth/WiNGPT2-Llama-3-8B-Chat"
  - "h2oai/h2o-danube3-4b-chat"
  - "Salesforce/Llama-xLAM-2-8b-fc-r"
  - "deepseek-ai/deepseek-coder-1.3b-instruct"
  - "AIDC-AI/Ovis2-8B"
  - "EleutherAI/pythia-410m"
  - "Qwen/Qwen2.5-Coder-1.5B-Instruct"
  - "EleutherAI/polyglot-ko-1.3b"
  - "allenai/OLMo-2-0425-1B"
  - "Efficient-Large-Model/Llama-3-VILA1.5-8B"
  - "PowerInfer/SmallThinker-3B-Preview"
  - "Intelligent-Internet/II-Medical-8B"
  - "nm-testing/TinyLlama-1.1B-compressed-tensors-kv-cache-scheme"
  - "baichuan-inc/Baichuan2-7B-Base"
  - "gghfez/gemma-3-4b-novision"
  - "EleutherAI/pythia-160m-deduped"
  - "bigcode/starcoder2-7b"
  - "beomi/Llama-3-KoEn-8B-Instruct-preview"
  - "ibm-granite/granite-3b-code-instruct-128k"
  - "kyutai/helium-1-2b"
  - "EleutherAI/gpt-neo-2.7B"
  - "nvidia/AceReason-Nemotron-1.1-7B"
  - "ibm-granite/granite-guardian-3.2-3b-a800m"
  - "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8-dynamic"
  - "defog/sqlcoder-7b-2"
  - "Qwen/Qwen1.5-MoE-A2.7B-Chat"
  - "HuggingFaceTB/SmolLM-360M"

